### ISSUE TITLE
No Gitter?

### ISSUE THREAD

**Issue by doriel** [amarildolucas/slack-ao#2]
O Meetus e a NodeSchool Luanda estão no Gitter.

**Comment by JoseCage** [comment]
@doriel atendendo que o repo trata direitamente do slack, não faz muito sentido dentro do mesmo repo ter listas de canais no gitter.. Talvez criando outro repo (**gitter-ao** por exemplo) ou mudando o nome do repo para se adequar quer ao **slack** como **gitter**..

**Comment by amarildolucas** [comment]
@doriel é exactamente o que o @JoseCage disse. Talvez outro repositório, apesar de que ficará tudo mais fragmentado! A minha escolha sobre o Slack recai unicamente por ele ser amplamente usado e ser o "queridinho" do meio.

**Comment by amarildolucas** [comment]
Irei fechar a **issue** por ser apenas uma lista para **slack**.
